name=FluxGarage RoboEyes for OLED and TFT Displays
version=1.1.1
author=Dennis Hoelscher & Owais <dennis@fluxgarage.com>
maintainer=Owais <owais@fluxgarage.com>
sentence=Draws smoothly animated robot eyes on OLED and TFT displays, using the Adafruit GFX library.
paragraph=Robot eye shapes are configurable in terms of width, height, border radius and space between. Several different mood expressions (happy, tired, angry, default) and animations (autoblinker, idle, laughing, confused) are available.
category=Display
url=https://github.com/owaiskreifeh/RoboEyes
architectures=*
depends=Adafruit GFX Library
